name: test conditional install

on:
  push:

jobs:
  install-job:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.2]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libicu-dev pkg-config
              poetry install  # --no-dev
              poetry add pyicu pycld2 polyglot
          elif [ "$RUNNER_OS" == "Windows" ]; then
              poetry install
              poetry add git+https://github.com/ffreemt/fast-langid.git
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash
